# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  Workers = 3 # max number of worker nodes
  Ver = '1.18.4' # Kubernetes Version to install
  
  #-------------#
  # Master Node #
  #-------------#
  
     config.vm.define "m-k8s" do |cfg|
       config.vm.box = "sysnet4admin/CentOS-k8s"
       cfg.vm.provider "vitualbox" do |vb|
         vb.name = "m-k8s(github_sambunarayan)"
         vb.cpus = 2
         vb.memory = 3072
         vb.customize ["modifyvm", :id, "--groups", "/k8s(github_sambunarayan)"]
       end
       cfg.vm.host_name = "m-k8s"
       cfg.vm.network "private_network", ip: "192.168.2.10"
       cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
       cfg.vm.synced_folder "../data", "/vagrant", disabled: true
       cfg.vm.provision "shell", path: "config.sh", args: Workers
       cfg.vm.provision "shell", path: "install_pkg.sh", args: [ Ver, "Main" ]
       cfg.vm.provision "shell", path: "master_node.sh"
     end
  
  #-------------#
  # Worker Node #
  #-------------#
  
  (1..Workers).each do |i|
    config.vm.define "w#{i}-k8s" do |cfg|
      config.vm.box = "sysnet4admin/CentOS-k8s"
      cfg.vm.provider "vitualbox" do |vb|
         vb.name = "w#{i}-k8s(github_sambunarayan)"
         vb.cpus = 1
         vb.memory = 2560
         vb.customize ["modifyvm", :id, "--groups", "/k8s(github_sambunarayan)"]
       end
       cfg.vm.host_name = "k#{i}-k8s"
       cfg.vm.network "private_network", ip: "192.168.2.10#{i}"
       cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}", auto_correct: true, id: "ssh"
       cfg.vm.synced_folder "../data", "/vagrant", disabled: true
       cfg.vm.provision "shell", path: "config.sh", args: Workers
       cfg.vm.provision "shell", path: "install_pkg.sh", args: Ver
       cfg.vm.provision "shell", path: "work_nodes.sh"
     end
   end
end